// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls whether Codex should apply DeepSeek-specific compatibility logic
 * to the active provider/model.
 */
export type DeepSeekCompatibility = "auto" | "enabled" | "disabled";
